all:
  hosts:
    postgresql1:
      ansible_host: postgresql1.clevo.home
      ansible_user: torake
  children:
    primary:
      hosts:
        postgresql1:
          private_ip: 192.168.122.203
          haproxy: true
          proxy_location: dc_1
          haproxy_configure: true
